data:
  type: '00'
  main_path: '../datasets/BIEL/00/'
  ground_truth: False
  pose_path: '../datasets/BIEL/00_IRI.txt'

parameters:
  rgb: True
  rectified: True 
  detector: 'lightglue' # detector for feature extraction (SIFT, ORB, or lightglue)
  threshold:  100
  max_depth: 300
  subset: null # subset of the dataset to use (null or number)
