data:
  type: '00'
  main_path: '../datasets/BIEL/'
  ground_truth: False
  pose_path: '../datasets/BIEL/'

parameters:
  rgb: True
  rectified: False  # Stereo rectify the images (I think this is not needed for IRI)
  detector: 'lightglue' # Detector for feature extraction (SIFT, ORB, or lightglue)
  depth_model: 'Complex' # Depth model for depth estimation (Simple, Complex, Distill or ZED)
  threshold:  0.25
  max_depth: 3000
  subset: null # subset of the dataset to use (null or number)
