data:
  type: '00'
  main_path: '../datasets/BIEL/'
  ground_truth: False
  pose_path: '../datasets/BIEL/'

parameters:
  rgb: True
  detector: 'LoFTR' # Detector for feature extraction (lightglue or LoFTR)
  depth_model: 'Complex' # Depth model for depth estimation (Simple, Complex, ZED, HighRes, HitNet or FastACVNet)
  threshold:  None
  max_depth: None
