data:
  type: '00'
  main_path: '../datasets/BIEL/'
  ground_truth: False
  pose_path: '../datasets/BIEL/'

parameters:
  rgb: True
  detector: 'lightglue' # lightglue, LoFTR, or Harris-SIFT
  depth_model: 'ZED' # Simple, Complex, ZED, HighRes, HitNet, or FastACVNet
  ransac_method: 'magsac++' # magsac++, lo_ransac, prosac, or ransac
  threshold:  None
  max_depth: None
