data:
  type: '00'
  main_path: '../datasets/BIEL/00/'
  ground_truth: False
  pose_path: '../datasets/BIEL/00_IRI.txt'

parameters:
  rgb: True
  rectified: False  # Stereo rectify the images (I think this is not needed for IRI)
  detector: 'lightglue' # detector for feature extraction (SIFT, ORB, or lightglue)
  depth_model: 'Distill' # depth model for depth estimation (Simple, Complex, or Distill)
  threshold:  0.25
  max_depth: 3000
  subset: null # subset of the dataset to use (null or number)
