data:
  type: '00'
  main_path: '../datasets/BIEL/'
  ground_truth: False
  pose_path: '../datasets/BIEL/'

parameters:
  rgb: True
  detector: 'lightglue' # Detector for feature extraction (SIFT, ORB, or lightglue)
  depth_model: 'HighRes' # Depth model for depth estimation (Simple, Complex, or ZED)
  threshold:  None
  max_depth: None
